# Generated by Django 6.0 on 2026-01-30 05:05

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Trade",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("symbol", models.CharField(max_length=20)),
                (
                    "side",
                    models.CharField(
                        choices=[("BUY", "Buy"), ("SELL", "Sell")], max_length=4
                    ),
                ),
                ("quantity", models.PositiveIntegerField()),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Execution price per unit",
                        max_digits=12,
                    ),
                ),
                (
                    "executed_at",
                    models.DateTimeField(
                        help_text="Actual trade execution time (exchange time)"
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                "ordering": ["executed_at"],
                "indexes": [
                    models.Index(
                        fields=["symbol"], name="trades_trad_symbol_d6aee8_idx"
                    ),
                    models.Index(
                        fields=["executed_at"], name="trades_trad_execute_6e665a_idx"
                    ),
                ],
            },
        ),
    ]
