# Generated by Django 6.0 on 2026-01-31 11:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("trades", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="RealizedTrade",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("symbol", models.CharField(max_length=50)),
                ("quantity", models.PositiveIntegerField()),
                ("buy_price", models.DecimalField(decimal_places=4, max_digits=12)),
                ("sell_price", models.DecimalField(decimal_places=4, max_digits=12)),
                ("pnl", models.DecimalField(decimal_places=4, max_digits=14)),
                ("realized_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name="trade",
            options={},
        ),
        migrations.RemoveIndex(
            model_name="trade",
            name="trades_trad_symbol_d6aee8_idx",
        ),
        migrations.RemoveIndex(
            model_name="trade",
            name="trades_trad_execute_6e665a_idx",
        ),
        migrations.AlterField(
            model_name="trade",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="trade",
            name="executed_at",
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name="trade",
            name="price",
            field=models.DecimalField(decimal_places=4, max_digits=12),
        ),
        migrations.AlterField(
            model_name="trade",
            name="symbol",
            field=models.CharField(max_length=50),
        ),
    ]
